### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by mattfarina** [peardeck/prometheus-user-monitoring#1]
Can you add a license file? Without an explicit license it's implicitly proprietary.

And, any JavaScript sent from the server to the browser is distributed making licenses notes there important, too.

**Comment by rileylark** [comment]
Hey @mattfarina - sure. Any preference on licensing?

**Comment by mattfarina** [comment]
Thanks for asking. Apache 2, MIT, or BSD are usually good choices for something like this.

**Comment by rileylark** [comment]
I decided on Apache 2 to match the Prometheus license. I haven't quite done an audit of what notice requirements the project might have because of dependencies, but I did make a quick note of the license at the top of the distributed JS.

Thanks for the feedback! These changes are in #2 . I'd love to hear what you think if you have time to check out the PR!

**Comment by rileylark** [comment]
I'm going to go ahead & merge it but would still appreciate your feedback on #2. Thanks for the suggestion & guidance!
